using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Requisicao.Models
{
    public class Bo
    {
        public string bostamp { get; set; }
        public string nmdos { get; set; }
        public decimal  obrano { get; set; }
        public DateTime? dataobra { get; set; }
        public string nome { get; set; }
        public decimal  totaldeb { get; set; }
        public decimal  etotaldeb { get; set; }
        public string tipo { get; set; }
        public DateTime? datafinal { get; set; }
        public decimal  smoe4 { get; set; }
        public decimal  smoe3 { get; set; }
        public decimal  smoe2 { get; set; }
        public decimal  smoe1 { get; set; }
        public decimal  moetotal { get; set; }
        public decimal  sdeb2 { get; set; }
        public decimal  sdeb1 { get; set; }
        public decimal  sdeb4 { get; set; }
        public decimal  sdeb3 { get; set; }
        public decimal  sqtt14 { get; set; }
        public decimal  sqtt13 { get; set; }
        public decimal  sqtt12 { get; set; }
        public decimal  sqtt11 { get; set; }
        public decimal  sqtt24 { get; set; }
        public decimal  sqtt23 { get; set; }
        public decimal  sqtt22 { get; set; }
        public decimal  sqtt21 { get; set; }
        public decimal  vqtt24 { get; set; }
        public decimal  vqtt23 { get; set; }
        public decimal  vqtt22 { get; set; }
        public decimal  vqtt21 { get; set; }
        public decimal  vendedor { get; set; }
        public string vendnm { get; set; }
        public decimal  stot1 { get; set; }
        public decimal  stot2 { get; set; }
        public decimal  stot3 { get; set; }
        public decimal  stot4 { get; set; }
        public decimal  no { get; set; }
        public string obranome { get; set; }
        public decimal  boano { get; set; }
        public DateTime? dataopen { get; set; }
        public DateTime? datafecho { get; set; }
        public bool fechada { get; set; }
        public decimal  nopat { get; set; }
        public decimal  total { get; set; }
        public decimal  tecnico { get; set; }
        public string tecnnm { get; set; }
        public decimal  nomquina { get; set; }
        public string maquina { get; set; }
        public string marca { get; set; }
        public string serie { get; set; }
        public string zona { get; set; }
        public string obs { get; set; }
        public string trab1 { get; set; }
        public string trab2 { get; set; }
        public string trab3 { get; set; }
        public string trab4 { get; set; }
        public string trab5 { get; set; }
        public decimal  ndos { get; set; }
        public decimal  custo { get; set; }
        public string moeda { get; set; }
        public decimal  estab { get; set; }
        public string morada { get; set; }
        public string local { get; set; }
        public string codpost { get; set; }
        public DateTime? ultfact { get; set; }
        public decimal  period { get; set; }
        public string tabela1 { get; set; }
        public string ncont { get; set; }
        public bool logi1 { get; set; }
        public bool logi2 { get; set; }
        public bool logi3 { get; set; }
        public bool logi4 { get; set; }
        public bool logi5 { get; set; }
        public bool logi6 { get; set; }
        public bool logi7 { get; set; }
        public bool logi8 { get; set; }
        public string segmento { get; set; }
        public bool impresso { get; set; }
        public string userimpresso { get; set; }
        public string fref { get; set; }
        public string ccusto { get; set; }
        public string ncusto { get; set; }
        public string cobranca { get; set; }
        public bool infref { get; set; }
        public bool lifref { get; set; }
        public decimal  esdeb1 { get; set; }
        public decimal  esdeb2 { get; set; }
        public decimal  esdeb3 { get; set; }
        public decimal  esdeb4 { get; set; }
        public decimal  evqtt21 { get; set; }
        public decimal  evqtt22 { get; set; }
        public decimal  evqtt23 { get; set; }
        public decimal  evqtt24 { get; set; }
        public decimal  estot1 { get; set; }
        public decimal  estot2 { get; set; }
        public decimal  estot3 { get; set; }
        public decimal  estot4 { get; set; }
        public decimal  etotal { get; set; }
        public decimal  ecusto { get; set; }
        public decimal  bo_2tdesc1 { get; set; }
        public decimal  bo_2tdesc2 { get; set; }
        public decimal  ebo_2tdes1 { get; set; }
        public decimal  ebo_2tdes2 { get; set; }
        public decimal  descc { get; set; }
        public decimal  edescc { get; set; }
        public decimal  bo_1tvall { get; set; }
        public decimal  bo_2tvall { get; set; }
        public decimal  ebo_1tvall { get; set; }
        public decimal  ebo_2tvall { get; set; }
        public decimal  bo11_bins { get; set; }
        public decimal  bo11_iva { get; set; }
        public decimal  ebo11_bins { get; set; }
        public decimal  ebo11_iva { get; set; }
        public decimal  bo21_bins { get; set; }
        public decimal  bo21_iva { get; set; }
        public decimal  ebo21_bins { get; set; }
        public decimal  ebo21_iva { get; set; }
        public decimal  bo31_bins { get; set; }
        public decimal  bo31_iva { get; set; }
        public decimal  ebo31_bins { get; set; }
        public decimal  ebo31_iva { get; set; }
        public decimal  bo41_bins { get; set; }
        public decimal  bo41_iva { get; set; }
        public decimal  ebo41_bins { get; set; }
        public decimal  ebo41_iva { get; set; }
        public decimal  bo51_bins { get; set; }
        public decimal  bo51_iva { get; set; }
        public decimal  ebo51_bins { get; set; }
        public decimal  ebo51_iva { get; set; }
        public decimal  bo61_bins { get; set; }
        public decimal  bo61_iva { get; set; }
        public decimal  ebo61_bins { get; set; }
        public decimal  ebo61_iva { get; set; }
        public decimal  bo12_bins { get; set; }
        public decimal  bo12_iva { get; set; }
        public decimal  ebo12_bins { get; set; }
        public decimal  ebo12_iva { get; set; }
        public decimal  bo22_bins { get; set; }
        public decimal  bo22_iva { get; set; }
        public decimal  ebo22_bins { get; set; }
        public decimal  ebo22_iva { get; set; }
        public decimal  bo32_bins { get; set; }
        public decimal  bo32_iva { get; set; }
        public decimal  ebo32_bins { get; set; }
        public decimal  ebo32_iva { get; set; }
        public decimal  bo42_bins { get; set; }
        public decimal  bo42_iva { get; set; }
        public decimal  ebo42_bins { get; set; }
        public decimal  ebo42_iva { get; set; }
        public decimal  bo52_bins { get; set; }
        public decimal  bo52_iva { get; set; }
        public decimal  ebo52_bins { get; set; }
        public decimal  ebo52_iva { get; set; }
        public decimal  bo62_bins { get; set; }
        public decimal  bo62_iva { get; set; }
        public decimal  ebo62_bins { get; set; }
        public decimal  ebo62_iva { get; set; }
        public decimal  bo_totp1 { get; set; }
        public decimal  bo_totp2 { get; set; }
        public decimal  ebo_totp1 { get; set; }
        public decimal  ebo_totp2 { get; set; }
        public bool edi { get; set; }
        public string memissao { get; set; }
        public string nome2 { get; set; }
        public string pastamp { get; set; }
        public string snstamp { get; set; }
        public string mastamp { get; set; }
        public string origem { get; set; }
        public decimal  orinopat { get; set; }
        public bool iiva { get; set; }
        public bool iunit { get; set; }
        public bool itotais { get; set; }
        public bool iunitiva { get; set; }
        public bool itotaisiva { get; set; }
        public string site { get; set; }
        public string pnome { get; set; }
        public decimal  pno { get; set; }
        public string cxstamp { get; set; }
        public string cxusername { get; set; }
        public string ssstamp { get; set; }
        public string ssusername { get; set; }
        public bool alldescli { get; set; }
        public bool alldesfor { get; set; }
        public string series { get; set; }
        public string series2 { get; set; }
        public string quarto { get; set; }
        public decimal  ocupacao { get; set; }
        public string tabela2 { get; set; }
        public string obstab2 { get; set; }
        public string iemail { get; set; }
        public string inome { get; set; }
        public decimal  situacao { get; set; }
        public string lang { get; set; }
        public string ean { get; set; }
        public string iecacodisen { get; set; }
        public bool boclose { get; set; }
        public DateTime? dtclose { get; set; }
        public string tpstamp { get; set; }
        public string tpdesc { get; set; }
        public bool emconf { get; set; }
        public string statuspda { get; set; }
        public bool aprovado { get; set; }
        public decimal  boid { get; set; }
        public string ousrinis { get; set; }
        public DateTime? ousrdata { get; set; }
        public string ousrhora { get; set; }
        public string usrinis { get; set; }
        public DateTime? usrdata { get; set; }
        public string usrhora { get; set; }
        public bool marcada { get; set; }
        public string u_gpgasto { get; set; }
        public decimal  u_hrs { get; set; }
        public decimal  u_kms { get; set; }
        public string u_matricul { get; set; }
        public string u_motorist { get; set; }
        public string u_tpgasto { get; set; }
        public decimal  u_totaldoc { get; set; }
    }
}
