using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Requisicao.Models
{
    public class St
    {
        public string ststamp { get; set; }
        public string @ref { get; set; }
        public string design { get; set; }
        public string familia { get; set; }
        public double stock { get; set; }
        public double epv1 { get; set; }
        public double pv1 { get; set; }
        public string forref { get; set; }
        public string fornecedor { get; set; }
        public string desc3 { get; set; }
        public string desc2 { get; set; }
        public string desc1 { get; set; }
        public string usr2 { get; set; }
        public string usr1 { get; set; }
        public DateTime validade { get; set; }
        public DateTime usaid { get; set; }
        public DateTime uintr { get; set; }
        public double usrqtt { get; set; }
        public double eoq { get; set; }
        public double pcult { get; set; }
        public double pcimp { get; set; }
        public string pcmoe { get; set; }
        public double pvcon { get; set; }
        public double pvultimo { get; set; }
        public double pv3 { get; set; }
        public double pv2 { get; set; }
        public string unidade { get; set; }
        public double ptoenc { get; set; }
        public double tabiva { get; set; }
        public string local { get; set; }
        public double fornec { get; set; }
        public double fornestab { get; set; }
        public double qttfor { get; set; }
        public double qttcli { get; set; }
        public double qttrec { get; set; }
        public DateTime udata { get; set; }
        public double pcusto { get; set; }
        public double pcpond { get; set; }
        public double qttacin { get; set; }
        public double qttacout { get; set; }
        public double qttvend { get; set; }
        public double pmvenda { get; set; }
        public double valin { get; set; }
        public double valout { get; set; }
        public double stmax { get; set; }
        public double stmin { get; set; }
        public string obs { get; set; }
        public string codigo { get; set; }
        public string uni2 { get; set; }
        public double conversao { get; set; }
        public bool ivaincl { get; set; }
        public bool nsujpp { get; set; }
        public double ecomissao { get; set; }
        public string imagem { get; set; }
        public double pv4 { get; set; }
        public double pv5 { get; set; }
        public double cpoc { get; set; }
        public string containv { get; set; }
        public string contacev { get; set; }
        public string contareo { get; set; }
        public string contacoe { get; set; }
        public double peso { get; set; }
        public bool bloqueado { get; set; }
        public bool fobloq { get; set; }
        public double mfornec { get; set; }
        public double mfornec2 { get; set; }
        public double pentrega { get; set; }
        public double consumo { get; set; }
        public bool baixr { get; set; }
        public double despimp { get; set; }
        public double mesescon { get; set; }
        public double marg1 { get; set; }
        public double marg2 { get; set; }
        public double marg3 { get; set; }
        public double marg4 { get; set; }
        public double marg5 { get; set; }
        public double diaspto { get; set; }
        public double diaseoq { get; set; }
        public string desc4 { get; set; }
        public string desc5 { get; set; }
        public string desc6 { get; set; }
        public bool noserie { get; set; }
        public bool clinica { get; set; }
        public bool vasilhame { get; set; }
        public double pbruto { get; set; }
        public double volume { get; set; }
        public bool usalote { get; set; }
        public bool texteis { get; set; }
        public double garantia { get; set; }
        public DateTime opendata { get; set; }
        public string faminome { get; set; }
        public string usr3 { get; set; }
        public string usr4 { get; set; }
        public string usr5 { get; set; }
        public double qttesp { get; set; }
        public double epv2 { get; set; }
        public double epv3 { get; set; }
        public double epv4 { get; set; }
        public double epv5 { get; set; }
        public double epcusto { get; set; }
        public double epcpond { get; set; }
        public double epcult { get; set; }
        public double epmvenda { get; set; }
        public double epvultimo { get; set; }
        public double epvcon { get; set; }
        public bool iva1incl { get; set; }
        public bool iva2incl { get; set; }
        public bool iva3incl { get; set; }
        public bool iva4incl { get; set; }
        public bool iva5incl { get; set; }
        public bool ivapcincl { get; set; }
        public bool stns { get; set; }
        public double stid { get; set; }
        public string tipodesc { get; set; }
        public string usr6 { get; set; }
        public double convunsup { get; set; }
        public string nccod { get; set; }
        public double massaliq { get; set; }
        public string url { get; set; }
        public double vaiwww { get; set; }
        public bool iectsug { get; set; }
        public double iectin { get; set; }
        public double eiectin { get; set; }
        public bool iectinii { get; set; }
        public string codfiscal { get; set; }
        public bool iecasug { get; set; }
        public double iecagrad { get; set; }
        public string iecaref { get; set; }
        public string iecarefnome { get; set; }
        public string txieca { get; set; }
        public string txiecanome { get; set; }
        public string iecautt { get; set; }
        public bool iecamultgrad { get; set; }
        public bool iecaisref { get; set; }
        public string site { get; set; }
        public bool qlook { get; set; }
        public string txtqlook { get; set; }
        public string imgqlook { get; set; }
        public string lang1 { get; set; }
        public string langdes1 { get; set; }
        public string lang2 { get; set; }
        public string langdes2 { get; set; }
        public string lang3 { get; set; }
        public string langdes3 { get; set; }
        public string lang4 { get; set; }
        public string langdes4 { get; set; }
        public string lang5 { get; set; }
        public string langdes5 { get; set; }
        public bool nexist { get; set; }
        public string statuspda { get; set; }
        public double qttcat { get; set; }
        public bool compnovo { get; set; }
        public bool ecovalor { get; set; }
        public double eecoval { get; set; }
        public double ecoval { get; set; }
        public bool ecopl { get; set; }
        public double eecopval { get; set; }
        public double ecopval { get; set; }
        public bool ecoel { get; set; }
        public double eecoeval { get; set; }
        public double ecoeval { get; set; }
        public bool ecorl { get; set; }
        public double eecorval { get; set; }
        public double ecorval { get; set; }
        public bool ecool { get; set; }
        public double eecooval { get; set; }
        public double ecooval { get; set; }
        public bool ecopilha { get; set; }
        public bool ecoacumulador { get; set; }
        public string ousrinis { get; set; }
        public DateTime ousrdata { get; set; }
        public string ousrhora { get; set; }
        public string usrinis { get; set; }
        public DateTime usrdata { get; set; }
        public string usrhora { get; set; }
        public bool marcada { get; set; }
        public bool qtttouch { get; set; }
        public bool semserprv { get; set; }
        public string contaieo { get; set; }
        public bool inactivo { get; set; }
        public bool orcamento { get; set; }
        public string refmo { get; set; }
        public string descrmo { get; set; }
        public double pcmo { get; set; }
        public double epcmo { get; set; }
        public double custo { get; set; }
        public double ecusto { get; set; }
        public double desci { get; set; }
        public double descii { get; set; }
        public DateTime datar { get; set; }
        public double pcdisp { get; set; }
        public double epcdisp { get; set; }
        public double pclab { get; set; }
        public double epclab { get; set; }
        public double custog { get; set; }
        public double ecustog { get; set; }
        public double custof { get; set; }
        public double ecustof { get; set; }
        public String unidadef { get; set; }
        public string ofcstamp { get; set; }
        public double codcmb { get; set; }
        public bool cancpos { get; set; }
        public DateTime datanovpv { get; set; }
        public string horanovpv { get; set; }
        public string tkhclass { get; set; }
        public bool stocktch { get; set; }
        public bool _mod { get; set; }
        public string restctprep { get; set; }
        public string idudesign { get; set; }
        public bool notimpcp { get; set; }
        public bool impfuelpos { get; set; }
        public bool amostra { get; set; }
        public bool sujinv { get; set; }
        public string u_strt { get; set; }
        public bool sujretirs { get; set; }
    }
}
